### ISSUE TITLE
can´t change state StandBy for isoft safe+

### ISSUE THREAD

**Issue by Claus1985** [arteck/ioBroker.judoisoft#23]
Hi Guys,

I´m trying to get control over my isoft safe+ in order to set it in standby during nightly watering of my garden.
Problem is, that although I can change the state in ioBroker nothing happens on the device.
Any advice on what I´m missing?

Thx and brgds,

Claus

**Comment by Tigor-Udo** [comment]
Hi,

i have the same problem here. I understood the standby data point to mean that the water treatment is interrupted for the time of the data point standby value.

If I misunderstood something, sorry.

From a purely logical point of view, nothing happens because I set the standby to true and the SBValue is 0, so I don't think anything starts. However, describing the value does not work.

Maybe you can give us an explanation for the data point.

thx

udo

**Comment by arteck** [comment]
LOG ??

**Comment by Claus1985** [comment]
ok Vorführeffekt... I set the log level to silly and started the adapter. Now everything works as it should... 
Only error I get is on adapter start but without negative impact:
![image](https://user-images.githubusercontent.com/69499563/182020166-0712419f-bd11-4f72-b73a-20c6641e0d9f.png)

**Comment by Tigor-Udo** [comment]
the log file indicates a change in the data point. After clicking the button, the value changes from 0 to 2 according to the log file. The log is attached as txt.

Thanks

udo
[logfile.txt](https://github.com/arteck/ioBroker.judoisoft/files/9229088/logfile.txt)

**Comment by arteck** [comment]
> ok Vorführeffekt... I set the log level to silly and started the adapter. Now it works as it should... Only error I get is on adapter start but without negative impact: ![image](https://user-images.githubusercontent.com/69499563/182020166-0712419f-bd11-4f72-b73a-20c6641e0d9f.png) One question remains though, does the standby only effect the water stop valve or does it also affect the water softening?
> 
> Thx!

check GIT verion again
